"""Cambios en el modelo users el campo update_at va a tener un valor por defecto

Revision ID: 7af51e82448a
Revises: b36662542ee8
Create Date: 2025-04-14 18:16:04.155113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af51e82448a'
down_revision: Union[str, None] = 'b36662542ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
